#!/bin/bash
# Copyright 2013 Scott Duckworth
#
# This file is part of django-sshkey.
#
# django-sshkey is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# django-sshkey is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with django-sshkey.  If not, see <http://www.gnu.org/licenses/>.

url="${SSHKEY_LOOKUP_URL:-http://localhost:8000/sshkey/lookup}"
if [ "x$SSH_KEY_FINGERPRINT" != "x" ]; then
  fingerprint="$SSH_KEY_FINGERPRINT"
else
  if [ "x$SSH_KEY" == "x" ] && ! read SSH_KEY; then
    echo "Error: cannot retrieve fingerprint from environment or stdin" >&2
    exit 1
  fi
  info="$(ssh-keygen -lf /dev/stdin <<< "$SSH_KEY")"
  if [ $? -ne 0 ]; then
    echo "Error: $info" >&2
    exit 1
  fi
  info=($info)
  fingerprint="${info[1]}"
fi
if type curl >/dev/null 2>&1; then
  exec curl -s -G "$url" --data-urlencode "fingerprint=${fingerprint}"
else
  exec wget -q -O - "${url}?fingerprint=${fingerprint}"
fi
